dist: trusty
language: go
go:
  - 1.8
sudo: required
go_import_path: github.com/mit-dci/lit
cache:
  directories:
  - bitcoin-0.15.0
  - litecoin-0.14.2
before_install:
  - go get github.com/mattn/goveralls
install:
  - sudo apt-get update
  - sudo apt-get install python3 python3-pip
  # Download bitcoind and add it to the path
  - ls bitcoin-0.15.0/bin/bitcoind || (wget https://bitcoincore.org/bin/bitcoin-core-0.15.0/bitcoin-0.15.0-x86_64-linux-gnu.tar.gz && tar xvf bitcoin-0.15.0-x86_64-linux-gnu.tar.gz)
  - PATH=$PATH:$PWD/bitcoin-0.15.0/bin
  # Download litecoind and add it to the path
  - ls litecoin-0.14.2/bin/litecoind || (wget https://download.litecoin.org/litecoin-0.14.2/linux/litecoin-0.14.2-x86_64-linux-gnu.tar.gz && tar xvf litecoin-0.14.2-x86_64-linux-gnu.tar.gz)
  - PATH=$PATH:$PWD/litecoin-0.14.2/bin
  - sudo pip3 install --upgrade pip
  - sudo pip3 install requests
  - sudo pip3 install websocket-client
script:
  - go get -v ./...
  - go test ./...
  - go build
  - test/test_basic.py -c reg --dumplogs
  - # test/test_basic.py -c ltr --dumplogs # litecoin currently broken. Disable test
  - test/test_break.py -c reg --dumplogs
  - $GOPATH/bin/goveralls -service=travis-ci
